Web servers: 
- DB Address: 
- DB Name: 
- DB Username: 
- DB Password: 
- Shared game server secret: 
- Password hasing pepper: 
- Access passwords (Max 20 chars): 
- Hashs of access passwords (passwordHashUtility.php): 
- Shared encryption secret: 

Dictator:
- DB Address: 
- DB Name: 
- DB Username: 
- DB Password: 